---
# tasks file for containerize-java-app-

- name: Copying source files
  copy:
    src: "{{item}}"
    dest: "{{app_path}}/"
  with_items: "{{app_srcs}}"

- name: Templating files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    "{{app_templates}}"

- name: Copying Dockerfile
  template:
    src:  "{{docker_file}}"
    dest: "{{app_path}}/Dockerfile"

- name: Building docker
  command: "docker build -t {{app_image_name}} ."
  args:
    chdir: "{{app_path}}"