---
# tasks file for containerize-java-app-

- name: Copy files
  copy:
    src: "{{item}}"
    dest: "{{app_path}}/"
  with_items: "{{app_srcs}}"

- name: Copying Dockerfile
  template:
    src:  "{{docker_file}}"
    dest: "{{app_path}}/Dockerfile"

- name: Building docker
  command: "docker build -t {{app_image_name}} ."
  args:
    chdir: "{{app_path}}"